### ISSUE TITLE
Member: clean up "lost ACKs"

### ISSUE THREAD

**Issue by graysonchao** [graysonchao/credis#1]
ACKs can be lost, resulting in buffered writes that never get flushed from local memory. This happens when the recipient of an ACK dies while the ACK is in flight. Since there is no buffering mechanism for acks in the CR paper (and any attempt to confirm the receipt of an ack runs into the 2 generals' problem) there should instead be a mechanism to clean up SNs when they are known to have been received by the tail.

**Comment by concretevitamin** [comment]
Hmm, doesn't the flushing mechanism do that?  I have some pending changes in [my branch](https://github.com/concretevitamin/credis-1/tree/flusher).

(Also, we should distinguish between "write request ack going back to the user" and "internal chain ack that cleans up the `sent` list".  IIRC, the latter is only an optimization in the protocol.  Also, credis has not implemented `sent` list yet.)
